/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newclock;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JOptionPane;

public class clockFrame extends javax.swing.JFrame {

    /**
     * Creates new form clockFrame
     */
    private int hour,minute,second;
    public clockFrame() {
        initComponents();
        String time=JOptionPane.showInputDialog(this,"Enter time in hh:mm:ss","Clock",JOptionPane.OK_CANCEL_OPTION);
        String []s=time.split(":",3);
        hour=Integer.parseInt(s[0]);
        minute=Integer.parseInt(s[1]);
        second=Integer.parseInt(s[2]);
        repaint();
    }
    @Override
    public void paint(Graphics g){
        super.paint(g);
        g.setColor(Color.BLUE);
        g.drawOval(100,100,300,300);
        double x=0,y=0;
        switch(hour){
            case 1:case 7:
                x=300;
                y=150;
                break;
            case 2:case 8:
                x=350;
                y=200;
                break;
            case 3:case 9:
                x=400;
                y=250;
                break;
            case 4:case 10:
                x=350;
                y=300;
                break;
            case 5:case 11:
                x=300;
                y=350;
                break;
            case 6:case 12:
                x=250;
                y=400;
                break;
           
         }
        if(hour>=6)
        {
            double temp=x;
            x=y;
            y=temp;
        }
        g.drawLine(250,250,(int)x,(int)y);
      int rangle=(minute*6);
       
        if (minute<=15)
       {
         rangle=90-rangle;
       }   
        else if(minute >270);
        {
            int temp=minute-270;
            rangle=270-temp;
        }
            
        double angle=Math.toRadians(rangle);


        x=(int)(120*Math.sin(angle))+250;
        y=(int)(120*Math.cos(angle))+250;  
        if(rangle<180)
        {   double temp=x;
            x=y;
            y=temp;
        }
        
        System.out.println("The value of x and y "+x+"\t"+y);
        g.drawLine(250,250,(int)x,(int)y);
         
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clockFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
}
